# This file was generated by GoReleaser. DO NOT EDIT.
class JiraToTripletex < Formula
  desc ""
  homepage "https://github.com/cobraz/jira-to-tripletex"
  version "1.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cobraz/jira-to-tripletex/releases/download/v1.2.1/jira-to-tripletex_1.2.1_Darwin_x86_64.tar.gz"
    sha256 "13b7df1c9150ad2e548d73b604815ba913c66149533d5623c3460ad08646de65"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cobraz/jira-to-tripletex/releases/download/v1.2.1/jira-to-tripletex_1.2.1_Linux_x86_64.tar.gz"
      sha256 "9c9b004cd2f8e5a166be8b775ef8be50ad09968f6f7bb09c4b95d584ce5fdda6"
    end
  end

  def install
    bin.install "jira-to-tripletex"
  end
end
