# This file was generated by GoReleaser. DO NOT EDIT.
class JiraToTripletex < Formula
  desc "Easily import Jira issues to a Tripletex project."
  homepage "https://github.com/cobraz/jira-to-tripletex"
  version "1.2.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cobraz/jira-to-tripletex/releases/download/v1.2.5/jira-to-tripletex_1.2.5_Darwin_x86_64.tar.gz"
    sha256 "3adb4370a1f753f14c058bdc02a50207f4e4747366fb687003eb50587265f4ea"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cobraz/jira-to-tripletex/releases/download/v1.2.5/jira-to-tripletex_1.2.5_Linux_x86_64.tar.gz"
      sha256 "5029682a7a96c889bbc211d20d25271ada9025408d773cfe0f0672e26f32e2dd"
    end
  end

  def install
    bin.install "jira-to-tripletex"
  end
end
