# This file was generated by GoReleaser. DO NOT EDIT.
class JiraToTripletex < Formula
  desc ""
  homepage "https://github.com/cobraz/jira-to-tripletex"
  version "1.2.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cobraz/jira-to-tripletex/releases/download/v1.2.3/jira-to-tripletex_1.2.3_Darwin_x86_64.tar.gz"
    sha256 "3cd0562be43241c19c07c3f76df3710087f55af89fe168f7f694e01bd7ff9d63"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cobraz/jira-to-tripletex/releases/download/v1.2.3/jira-to-tripletex_1.2.3_Linux_x86_64.tar.gz"
      sha256 "be551578c3664f0c2de8fd3923197b6ae570aca1fc44418a3aa2a70eb6395fca"
    end
  end

  def install
    bin.install "jira-to-tripletex"
  end
end
