# This file was generated by GoReleaser. DO NOT EDIT.
class TripplTimely < Formula
  desc "Easily import Jira issues to a Tripletex project."
  homepage "https://github.com/cobraz/trippl-timely"
  version "2.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cobraz/trippl-timely/releases/download/v2.0.0/trippl-timely_2.0.0_Darwin_x86_64.tar.gz"
    sha256 "abe7ab3ed0499f582e08c76696b0b6cb4564ee1114139581bc52bf12ac549e69"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cobraz/trippl-timely/releases/download/v2.0.0/trippl-timely_2.0.0_Linux_x86_64.tar.gz"
      sha256 "d53d811c580361ac63e8fb0cece7b8ead1e0eccc472b79544567f5dd569ae601"
    end
  end

  def install
    bin.install "trippl-timely"
  end
end
