# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TripplTimely < Formula
  desc "Easily import Jira issues to a Tripletex project."
  homepage "https://github.com/cobraz/trippl-timely"
  version "2.1.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cobraz/trippl-timely/releases/download/v2.1.2/trippl-timely_2.1.2_Darwin_x86_64.tar.gz"
      sha256 "c3881d1d260a5b0ee707bbb1bc78973cd53942d7babf43c6922820497e9f8066"
    end
    if Hardware::CPU.arm?
      url "https://github.com/cobraz/trippl-timely/releases/download/v2.1.2/trippl-timely_2.1.2_Darwin_arm64.tar.gz"
      sha256 "d3579e5c6ef5ec1abcf8e5865f0eca069d8510f5c1bc2e0b184e444457399f8c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cobraz/trippl-timely/releases/download/v2.1.2/trippl-timely_2.1.2_Linux_x86_64.tar.gz"
      sha256 "160b6c5d701edb6a7df5b7c0e7c5016d065b84ea0d783fbbf88ec7f01ad8ae0a"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cobraz/trippl-timely/releases/download/v2.1.2/trippl-timely_2.1.2_Linux_arm64.tar.gz"
      sha256 "9a038f3baef4061b8759e96b729bd8947fe82cb28f2adf021d08261fbb12fa13"
    end
  end

  def install
    bin.install "trippl-timely"
  end
end
