# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XlsxMxlookup < Formula
  desc "Loop through a list of domains and return their MX records"
  homepage "https://github.com/cobraz/xlsx-mxlookup"
  version "1.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cobraz/xlsx-mxlookup/releases/download/v1.2.3/xlsx-mxlookup_1.2.3_Darwin_x86_64.tar.gz"
      sha256 "b8eaead9ba25d7dee2c53c6a9828c74e009d6f76f031f2039e733657e8273d68"

      def install
        bin.install "xlsx-mxlookup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cobraz/xlsx-mxlookup/releases/download/v1.2.3/xlsx-mxlookup_1.2.3_Darwin_arm64.tar.gz"
      sha256 "4d3c0eb11cd6d0d9bb2a8e78360c9d4f491f05e73810fce08e3e9d82561237db"

      def install
        bin.install "xlsx-mxlookup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cobraz/xlsx-mxlookup/releases/download/v1.2.3/xlsx-mxlookup_1.2.3_Linux_arm64.tar.gz"
      sha256 "0cfcf588cb81d7ddc6659b046a7bf6f79ca2c146b86137cbe09b9d8ad74e57bf"

      def install
        bin.install "xlsx-mxlookup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cobraz/xlsx-mxlookup/releases/download/v1.2.3/xlsx-mxlookup_1.2.3_Linux_x86_64.tar.gz"
      sha256 "db9adbb4cc104e6e4469933e206cc701054810d9e0a61789c6c3c21292ab5a74"

      def install
        bin.install "xlsx-mxlookup"
      end
    end
  end
end
